### ISSUE TITLE
Daterange working as a modal 

### ISSUE THREAD

**Issue by daherlive** [ZestfulNation/vue-hotel-datepicker#318]
I need to make it so that when I call the action to open the calendar, it can be like a modal, open to the center. How could it be possible?

**Comment by matiasperrone** [comment]
I think this go outside the scope of this component, and this can be easily achieved by render the calendar inline inside a modal (a div with the proper z-index value) and capture the changes yourself by using the events.

Because a modal depends highly on your design.

Besides, the team is trying to allocate time to move to Vue 3.

Do you agree?
